stages:
  - test
  - artifact

.docker_tags: &docker_europe_tags
  tags:
    - linux
    - docker
    - europe

build archive:
  <<: *docker_europe_tags
  image: docker-local.jgit.me/infrastructure-images-ansible
  stage: artifact
  script:
   - echo tag=${CI_COMMIT_TAG} pipe=${CI_PIPELINE_ID}
   - "if [ -z ${CI_COMMIT_TAG} ]; then export VERSION=dev-${CI_COMMIT_REF_SLUG}; else export VERSION=${CI_COMMIT_TAG}; fi"
   - export FILENAME=ansible-${CI_PROJECT_NAME}-${VERSION}.tgz
   - echo "Filename ${FILENAME}"
   - ls -lah
   - ansible-galaxy install -r requirements.yml -p roles
   - tar -cz --exclude-vcs -f ../${FILENAME} .
   - export AF_PASSWORD=`vault read -field=token secret/artifactory/${AF_USERNAME}`
   - curl -u${AF_USERNAME}:${AF_PASSWORD} -XPUT https://artifactory.jgit.me/artifactory/ansible/ -T ../${FILENAME}

