- name: facelessvpnserver-system.role
  src: git@jgit.me:ansible/roles/facelessvpnserver-system.role.git
  scm: git

- name: facelessvpnserver-freeradius.role
  src: git@jgit.me:ansible/roles/facelessvpnserver-freeradius.role.git
  scm: git

- name: facelessvpnserver-strongswan.role
  src: git@jgit.me:ansible/roles/facelessvpnserver-strongswan.role.git
  scm: git

- name: facelessvpnserver-openvpn.role
  src: git@jgit.me:ansible/roles/facelessvpnserver-openvpn.role.git
  scm: git

- name: firewall.role
  src: git@jgit.me:ansible/roles/firewall.role.git
  scm: git
