- name: base-setup.role
  src: git@jgit.me:ansible/roles/base-setup.role.git
  scm: git

- name: zabbix.role
  src: git@jgit.me:ansible/roles/zabbix.role.git
  scm: git
  version: origin/master

- name: custom-handlers.role
  src: git@jgit.me:ansible/roles/custom-handlers.role.git
  scm: git

- name: local_accounts.role
  src: git@jgit.me:ansible/roles/local_accounts.role.git
  scm: git
