---
- import_tasks: el7.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- import_tasks: el6.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
