---
iptables_config: |
  *filter
  -A INPUT -p icmp -j ACCEPT
  -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
  -A INPUT -s 127.0.0.1/32 -j ACCEPT
  -A INPUT -p tcp -m tcp --dport 22468 -j ACCEPT
  -A INPUT -j DROP
  COMMIT
