---

- hosts: all
  gather_facts: false

  roles:
    - facelessvpnserver-system.role
    - facelessvpnserver-strongswan.role
    - facelessvpnserver-freeradius.role
    - firewall.role

  pre_tasks:

    - name: Check server is not RKN blacklisted
      uri:
        url: "http://ip-checker.service.{{ project }}.consul/check?ip={{ inventory_hostname }}"
        method: GET
        return_content: yes
      register: this
      failed_when: "'false' not in this.content"
      delegate_to: localhost
      become: false

    - name: Wait for server up
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: gather facts
      setup:

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        state: disabled

    - name: "prepare install epel-release"
      raw: yum -y install epel-release
      changed_when: false

    - name: "prepare: install python2-pip"
      raw: yum -y install python2-pip
      changed_when: false
